/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvst_wrapper_communication_VSTV23ToHost */

#ifndef _Included_jvst_wrapper_communication_VSTV23ToHost
#define _Included_jvst_wrapper_communication_VSTV23ToHost
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: logBasePath */
/* Inaccessible static: logFileName */
/* Inaccessible static: logEnabled */
#undef jvst_wrapper_communication_VSTV23ToHost_CANDO_DONT_KNOW
#define jvst_wrapper_communication_VSTV23ToHost_CANDO_DONT_KNOW 0L
#undef jvst_wrapper_communication_VSTV23ToHost_CANDO_YES
#define jvst_wrapper_communication_VSTV23ToHost_CANDO_YES 1L
#undef jvst_wrapper_communication_VSTV23ToHost_CANDO_NO
#define jvst_wrapper_communication_VSTV23ToHost_CANDO_NO -1L
#undef jvst_wrapper_communication_VSTV23ToHost_VST_LANG_ENGLISH
#define jvst_wrapper_communication_VSTV23ToHost_VST_LANG_ENGLISH 1L
#undef jvst_wrapper_communication_VSTV23ToHost_VST_LANG_GERMAN
#define jvst_wrapper_communication_VSTV23ToHost_VST_LANG_GERMAN 2L
#undef jvst_wrapper_communication_VSTV23ToHost_VST_LANG_FRENCH
#define jvst_wrapper_communication_VSTV23ToHost_VST_LANG_FRENCH 3L
#undef jvst_wrapper_communication_VSTV23ToHost_VST_LANG_ITALIAN
#define jvst_wrapper_communication_VSTV23ToHost_VST_LANG_ITALIAN 4L
#undef jvst_wrapper_communication_VSTV23ToHost_VST_LANG_SPANISH
#define jvst_wrapper_communication_VSTV23ToHost_VST_LANG_SPANISH 5L
#undef jvst_wrapper_communication_VSTV23ToHost_VST_LANG_JAPANESE
#define jvst_wrapper_communication_VSTV23ToHost_VST_LANG_JAPANESE 6L
/*
 * Class:     jvst_wrapper_communication_VSTV23ToHost
 * Method:    setPanLaw
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_jvst_wrapper_communication_VSTV23ToHost_setPanLaw
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     jvst_wrapper_communication_VSTV23ToHost
 * Method:    beginLoadBank
 * Signature: (Ljvst/wrapper/valueobjects/VSTPatchChunkInfo;)I
 */
JNIEXPORT jint JNICALL Java_jvst_wrapper_communication_VSTV23ToHost_beginLoadBank
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jvst_wrapper_communication_VSTV23ToHost
 * Method:    beginLoadProgram
 * Signature: (Ljvst/wrapper/valueobjects/VSTPatchChunkInfo;)I
 */
JNIEXPORT jint JNICALL Java_jvst_wrapper_communication_VSTV23ToHost_beginLoadProgram
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jvst_wrapper_communication_VSTV23ToHost
 * Method:    copySpeaker
 * Signature: (Ljvst/wrapper/valueobjects/VSTSpeakerProperties;Ljvst/wrapper/valueobjects/VSTSpeakerProperties;)Z
 */
JNIEXPORT jboolean JNICALL Java_jvst_wrapper_communication_VSTV23ToHost_copySpeaker
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jvst_wrapper_communication_VSTV23ToHost
 * Method:    matchArrangement
 * Signature: (Ljvst/wrapper/valueobjects/VSTSpeakerArrangement;Ljvst/wrapper/valueobjects/VSTSpeakerArrangement;)Z
 */
JNIEXPORT jboolean JNICALL Java_jvst_wrapper_communication_VSTV23ToHost_matchArrangement
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
