/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvst_wrapper_communication_VSTV21ToHost */

#ifndef _Included_jvst_wrapper_communication_VSTV21ToHost
#define _Included_jvst_wrapper_communication_VSTV21ToHost
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: logBasePath */
/* Inaccessible static: logFileName */
/* Inaccessible static: logEnabled */
#undef jvst_wrapper_communication_VSTV21ToHost_CANDO_DONT_KNOW
#define jvst_wrapper_communication_VSTV21ToHost_CANDO_DONT_KNOW 0L
#undef jvst_wrapper_communication_VSTV21ToHost_CANDO_YES
#define jvst_wrapper_communication_VSTV21ToHost_CANDO_YES 1L
#undef jvst_wrapper_communication_VSTV21ToHost_CANDO_NO
#define jvst_wrapper_communication_VSTV21ToHost_CANDO_NO -1L
#undef jvst_wrapper_communication_VSTV21ToHost_VST_LANG_ENGLISH
#define jvst_wrapper_communication_VSTV21ToHost_VST_LANG_ENGLISH 1L
#undef jvst_wrapper_communication_VSTV21ToHost_VST_LANG_GERMAN
#define jvst_wrapper_communication_VSTV21ToHost_VST_LANG_GERMAN 2L
#undef jvst_wrapper_communication_VSTV21ToHost_VST_LANG_FRENCH
#define jvst_wrapper_communication_VSTV21ToHost_VST_LANG_FRENCH 3L
#undef jvst_wrapper_communication_VSTV21ToHost_VST_LANG_ITALIAN
#define jvst_wrapper_communication_VSTV21ToHost_VST_LANG_ITALIAN 4L
#undef jvst_wrapper_communication_VSTV21ToHost_VST_LANG_SPANISH
#define jvst_wrapper_communication_VSTV21ToHost_VST_LANG_SPANISH 5L
#undef jvst_wrapper_communication_VSTV21ToHost_VST_LANG_JAPANESE
#define jvst_wrapper_communication_VSTV21ToHost_VST_LANG_JAPANESE 6L
/*
 * Class:     jvst_wrapper_communication_VSTV21ToHost
 * Method:    beginEdit
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jvst_wrapper_communication_VSTV21ToHost_beginEdit
  (JNIEnv *, jobject, jint);

/*
 * Class:     jvst_wrapper_communication_VSTV21ToHost
 * Method:    endEdit
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jvst_wrapper_communication_VSTV21ToHost_endEdit
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
